/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20Token } from "./ERC20Token";
export * as factories from "./factories";
export { ERC20Token__factory } from "./factories/ERC20Token__factory";
